### ISSUE TITLE
Change Edited Javascript Files into Typescript to meet Project Requirements (for Sprint 2)

### ISSUE THREAD

**Issue by alanouda2** [CMU-17313Q/fall23-nodebb-nirvana#24]
## High-level Description:

As part of our ongoing project, it has become necessary to adhere to project requirements that mandate the use of TypeScript. We have identified certain JavaScript files that have been edited, and we need to convert them into TypeScript to align with these requirements and ensure code consistency. To meet project requirements and maintain code consistency, we intend to convert previously edited JavaScript files into TypeScript.

## Details:

- Identify the specific JavaScript files that require conversion to TypeScript.
- Refactor the identified JavaScript files to TypeScript, including updating type annotations and ensuring TypeScript best practices.
- Verify that the converted TypeScript code retains the same functionality as the original JavaScript.

## Estimated effort:

- Review and identification of JavaScript files for conversion: 2 hours
- Conversion of JavaScript files to TypeScript: 6 hours
- Testing and debugging of converted code: 2 hours

## Dependencies:
None

## Acceptance criteria:

- The identified JavaScript files have been successfully converted to TypeScript.
- TypeScript type annotations and best practices are followed in the converted code.
- The functionality of the code remains unchanged after the conversion.
- Ensure that the build process accommodates TypeScript files and compiles them without errors.

**Comment by Inverseit** [comment]
We have not created any new `.js` files, so it is not required.
