### ISSUE TITLE
Write Tests for new features to Ensure Compatibility and Integration  (for Sprint 2)

### ISSUE THREAD

**Issue by alanouda2** [CMU-17313Q/fall23-nodebb-nirvana#25]
## High-level Description:
As we continue to develop and introduce new features into our project, it is essential to maintain code quality and ensure that these features are compatible with existing functionality. To achieve this, we need to write comprehensive tests for the new features to validate their compatibility and integration with the existing codebase. To maintain code quality and ensure seamless integration, we propose writing tests for the new features introduced in the project.

## Details:

- Identify the new features that require testing to ensure compatibility and integration.
- Develop test cases and test suites that cover the functionality of the new features.
- Execute tests to verify that the new features work as expected and do not introduce regressions.
- Ensure that the tests are well-documented and follow testing best practices.

## Estimated effort:

- Review and identification of features requiring tests: 2 hours
- Test case development and documentation: 4 hours
- Test execution and debugging: 3 hours

## Dependencies:

None

## Acceptance criteria:

- Test cases for the identified new features have been written and are part of the project's test suite.
- The test cases cover the functionality of the new features and verify their compatibility with existing code.
- Test execution results confirm that the new features work as expected and do not introduce regressions.
- Tests are well-documented and adhere to testing best practices.

**Comment by Inverseit** [comment]
This issue should be broken down into several parts:

- Testing for backend post for anonymization 
- Testing Topic Anonymization 
- Testing Avatar Template Anonymization 
- Post-Editing Test 
- User Registration Testing 
- Test for private post [pending]

We will create separate issues for each part.
